name: equustore
description: "Sistema de facturación moderno."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Dependencias clave
  google_fonts: ^6.1.0
  flutter_riverpod: ^2.4.0
  lucide_icons: ^0.257.0
  window_manager: ^0.3.9
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  # CORREGIDO: Bajamos de 6.0.0 a 2.0.0 para evitar errores de resolución
  flutter_lints: ^2.0.0 

flutter:
  uses-material-design: true